### PR TITLE
Patch for clear method

### PR DESCRIPTION
**Pull request by ghost**
Patch for the issue about Clear() method, please refer to [#2](https://github.com/JN-Jones/visitor-log/issues/2)
### What has been changed ?
- Added a parameter into the config.php called `datetype`, it has two options : 
  - `timestamps` - If the user is actually using **TRUE** timestamps, he has to switch to this the `datetype`
  - `date`\- If the user is using complete datetime, it's the default option as Laravel isn't using timestamps with Carbon API on the 4.2, 4.1 and neither on the 4.0 but the user can switch to timestamps.
- Added a check in the clear method, it will change the delete method depending on what type of date is currently using the user.

### CODE REVIEW

**Comment by JN-Jones** [comment]
Looks good from a quick look, I'll test it properly later. However one little thing: instead of

``` php
switch($var) {
  case 1:
     // Query 1
  case 2:
     // Query 2
  default:
     // Query 2
}
```

You could do:

``` php
switch($var) {
  case 1:
     // Query 1
  case 2:
  default:
     // Query 2
}
```

**Comment by JN-Jones** [comment]
I was also thinking about using `getDateFormat` to detect automatically what format should be used (as there are multiple ways to store a date)

**Comment by ghost** [comment]
Sound great for `getDateFormat`, I'll give a try.

**Comment by JN-Jones** [comment]
Thanks :D I should have time soon to work a bit more with laravel again.

**Comment by ghost** [comment]
Try was successful, it was deleting after time, even when I overrode `getDateFormat` to return another Date Format.

**Comment by JN-Jones** [comment]
Ok, I'll try to test this tomorrow or the day after.

**Comment by ghost** [comment]
Any update ?

**Comment by JN-Jones** [comment]
Sorry, I'm really busy atm - exams, release time for @mybb and some personal things. Don't know when I've more time

**Comment by ghost** [comment]
Don't know if you'll be updating or maintaining this package anymore, if you would not maintain this package, could I just fork or create a new repository with credits in order to continue to maintain this package (which is helpful)

**Comment by JN-Jones** [comment]
I plan to maintain the package but it's one of my lower priorities. However feel free to fork the package if you want to ;)

**Pull request closed without merging**
